#!/bin/sh
# todo finish him
# http://www.gdal.org/ogr2ogr.html
# https://github.com/mbostock/topojson/wiki/Command-Line-Reference

if [ ! -d "out" ]; then
    mkdir -p out/json
    echo "Creating the out directory out/json"
fi

# $1 is the file for the generated shp file
# $2 this is the ogr2ogr filter e.g. "ADM0_A3 NOT IN ('ATA')" > don't include antartica in the generated shp file
# $3 is the shape file which will be filtered
create_shp () {
    out=out/$1
    echo $out

    if [ -d $out ]; then
        rm -rf $out
    fi

    mkdir $out
    ogr2ogr -f "ESRI Shapefile" -where "$2" $out/$1 shpfiles/$3
}

# Creates the topoJson file from the filtered shp file.
# Expects 3 params:
# $1 is the file for the generated json file
# $2 is the shape file which is used to create the land
# $3 is the shape file which is used to create the countries
create_topojson () {
    if [ -f "$1" ]; then
        rm $1
    fi

    tmpDir=$1.tmp
    if [ ! -d $tmpDir ]; then
        mkdir -p $tmpDir
        echo "Creating the temp directory $tmpDir"
    fi

    topojson -o $tmpDir/tmp.json -q 1e5 --id-property=+iso_n3 -p iso_a2,adm0_a3,gn_a1_code,gns_region,name -- land=$3 countries=$3
    topojson-merge -o $1 --io=land --oo=land --no-key -- $tmpDir/tmp.json
    rm -rf $tmpDir
}

generate_topojson () {
    create_shp "$1.shp" "$2" "ne_10m_admin_0_countries.shp"
    create_topojson "out/json/region/$1/topo.json" "ne_10m_land.shp" "out/$1.shp/$1.shp"
}

# with provinces
generate_topojson () {
    create_shp "$1-s.shp" "$2" "ne_10m_admin_1_states_provinces.shp"
    create_topojson "out/json/countries/$1/topo-s.json" "ne_10m_land.shp" "out/$1-s.shp/$1-s.shp"
}

generate_topojson "AW" "ADM0_A3 IN ('ABW')"
generate_topojson "AF" "ADM0_A3 IN ('AFG')"
generate_topojson "AO" "ADM0_A3 IN ('AGO')"
generate_topojson "AI" "ADM0_A3 IN ('AIA')"
generate_topojson "AL" "ADM0_A3 IN ('ALB')"
generate_topojson "AX" "ADM0_A3 IN ('ALA')"
generate_topojson "AD" "ADM0_A3 IN ('AND')"
generate_topojson "AE" "ADM0_A3 IN ('ARE')"
generate_topojson "AR" "ADM0_A3 IN ('ARG')"
generate_topojson "AM" "ADM0_A3 IN ('ARM')"
generate_topojson "AS" "ADM0_A3 IN ('ASM')"
generate_topojson "AU" "ADM0_A3 IN ('AUS')"
generate_topojson "TF" "ADM0_A3 IN ('ATF')"
generate_topojson "AG" "ADM0_A3 IN ('ATG')"
generate_topojson "AU" "ADM0_A3 IN ('AUS')"
generate_topojson "AT" "ADM0_A3 IN ('AUT')"
generate_topojson "AZ" "ADM0_A3 IN ('AZE')"
generate_topojson "BI" "ADM0_A3 IN ('BDI')"
generate_topojson "BE" "ADM0_A3 IN ('BEL')"
generate_topojson "BJ" "ADM0_A3 IN ('BEN')"
generate_topojson "BF" "ADM0_A3 IN ('BFA')"
generate_topojson "BD" "ADM0_A3 IN ('BGD')"
generate_topojson "BG" "ADM0_A3 IN ('BGR')"
generate_topojson "BH" "ADM0_A3 IN ('BHR')"
generate_topojson "BS" "ADM0_A3 IN ('BHS')"
generate_topojson "BA" "ADM0_A3 IN ('BIH')"
generate_topojson "BL" "ADM0_A3 IN ('BLM')"
generate_topojson "BY" "ADM0_A3 IN ('BLR')"
generate_topojson "BZ" "ADM0_A3 IN ('BLZ')"
generate_topojson "BM" "ADM0_A3 IN ('BMU')"
generate_topojson "BO" "ADM0_A3 IN ('BOL')"
generate_topojson "BR" "ADM0_A3 IN ('BRA')"
generate_topojson "BB" "ADM0_A3 IN ('BRB')"
generate_topojson "BN" "ADM0_A3 IN ('BRN')"
generate_topojson "BT" "ADM0_A3 IN ('BTN')"
generate_topojson "BW" "ADM0_A3 IN ('BWA')"
generate_topojson "CF" "ADM0_A3 IN ('CAF')"
generate_topojson "CA" "ADM0_A3 IN ('CAN')"
generate_topojson "CH" "ADM0_A3 IN ('CHE')"
generate_topojson "CL" "ADM0_A3 IN ('CHL')"
generate_topojson "CN" "ADM0_A3 IN ('CHN')"
generate_topojson "CI" "ADM0_A3 IN ('CIV')"
generate_topojson "CM" "ADM0_A3 IN ('CMR')"
generate_topojson "CD" "ADM0_A3 IN ('COD')"
generate_topojson "CG" "ADM0_A3 IN ('COG')"
generate_topojson "CK" "ADM0_A3 IN ('COK')"
generate_topojson "CO" "ADM0_A3 IN ('COL')"
generate_topojson "KM" "ADM0_A3 IN ('COM')"
generate_topojson "CV" "ADM0_A3 IN ('CPV')"
generate_topojson "CR" "ADM0_A3 IN ('CRI')"
generate_topojson "CU" "ADM0_A3 IN ('CUB')"
generate_topojson "CW" "ADM0_A3 IN ('CUW')"
generate_topojson "KY" "ADM0_A3 IN ('CYM')"
generate_topojson "CY" "ADM0_A3 IN ('CYP')"
generate_topojson "CY" "ADM0_A3 IN ('CYP')"
generate_topojson "CZ" "ADM0_A3 IN ('CZE')"
generate_topojson "DE" "ADM0_A3 IN ('DEU')"
generate_topojson "DJ" "ADM0_A3 IN ('DJI')"
generate_topojson "DM" "ADM0_A3 IN ('DMA')"
generate_topojson "DK" "ADM0_A3 IN ('DNK')"
generate_topojson "DO" "ADM0_A3 IN ('DOM')"
generate_topojson "DZ" "ADM0_A3 IN ('DZA')"
generate_topojson "EC" "ADM0_A3 IN ('ECU')"
generate_topojson "EG" "ADM0_A3 IN ('EGY')"
generate_topojson "ER" "ADM0_A3 IN ('ERI')"
generate_topojson "ES" "ADM0_A3 IN ('ESP')"
generate_topojson "EE" "ADM0_A3 IN ('EST')"
generate_topojson "ET" "ADM0_A3 IN ('ETH')"
generate_topojson "FI" "ADM0_A3 IN ('FIN')"
generate_topojson "FJ" "ADM0_A3 IN ('FJI')"
generate_topojson "FK" "ADM0_A3 IN ('FLK')"
generate_topojson "FR" "ADM0_A3 IN ('FRA') AND TYPE_EN like 'Metropolitan%'"
generate_topojson "FO" "ADM0_A3 IN ('FRO')"
generate_topojson "FM" "ADM0_A3 IN ('FSM')"
generate_topojson "GA" "ADM0_A3 IN ('GAB')"
generate_topojson "GB" "ADM0_A3 IN ('GBR')"
generate_topojson "GE" "ADM0_A3 IN ('GEO')"
generate_topojson "GG" "ADM0_A3 IN ('GGY')"
generate_topojson "GH" "ADM0_A3 IN ('GHA')"
generate_topojson "GN" "ADM0_A3 IN ('GIN')"
generate_topojson "GM" "ADM0_A3 IN ('GMB')"
generate_topojson "GW" "ADM0_A3 IN ('GNB')"
generate_topojson "GQ" "ADM0_A3 IN ('GNQ')"
generate_topojson "GR" "ADM0_A3 IN ('GRC')"
generate_topojson "GD" "ADM0_A3 IN ('GRD')"
generate_topojson "GL" "ADM0_A3 IN ('GRL')"
generate_topojson "GT" "ADM0_A3 IN ('GTM')"
generate_topojson "GU" "ADM0_A3 IN ('GUM')"
generate_topojson "GY" "ADM0_A3 IN ('GUY')"
generate_topojson "HK" "ADM0_A3 IN ('HKG')"
generate_topojson "HM" "ADM0_A3 IN ('HMD')"
generate_topojson "HN" "ADM0_A3 IN ('HND')"
generate_topojson "HR" "ADM0_A3 IN ('HRV')"
generate_topojson "HT" "ADM0_A3 IN ('HTI')"
generate_topojson "HU" "ADM0_A3 IN ('HUN')"
generate_topojson "ID" "ADM0_A3 IN ('IDN')"
generate_topojson "IM" "ADM0_A3 IN ('IMN')"
generate_topojson "IN" "ADM0_A3 IN ('IND')"
generate_topojson "IO" "ADM0_A3 IN ('IOT')"
generate_topojson "IE" "ADM0_A3 IN ('IRL')"
generate_topojson "IR" "ADM0_A3 IN ('IRN')"
generate_topojson "IQ" "ADM0_A3 IN ('IRQ')"
generate_topojson "IS" "ADM0_A3 IN ('ISL')"
generate_topojson "IL" "ADM0_A3 IN ('ISR')"
generate_topojson "IT" "ADM0_A3 IN ('ITA')"
generate_topojson "JM" "ADM0_A3 IN ('JAM')"
generate_topojson "JE" "ADM0_A3 IN ('JEY')"
generate_topojson "JO" "ADM0_A3 IN ('JOR')"
generate_topojson "JP" "ADM0_A3 IN ('JPN')"
generate_topojson "KZ" "ADM0_A3 IN ('KAZ')"
generate_topojson "KE" "ADM0_A3 IN ('KEN')"
generate_topojson "KG" "ADM0_A3 IN ('KGZ')"
generate_topojson "KH" "ADM0_A3 IN ('KHM')"
generate_topojson "KI" "ADM0_A3 IN ('KIR')"
generate_topojson "KN" "ADM0_A3 IN ('KNA')"
generate_topojson "KR" "ADM0_A3 IN ('KOR')"
generate_topojson "RS" "ADM0_A3 IN ('SRB')"
generate_topojson "KW" "ADM0_A3 IN ('KWT')"
generate_topojson "LA" "ADM0_A3 IN ('LAO')"
generate_topojson "LB" "ADM0_A3 IN ('LBN')"
generate_topojson "LR" "ADM0_A3 IN ('LBR')"
generate_topojson "LY" "ADM0_A3 IN ('LBY')"
generate_topojson "LC" "ADM0_A3 IN ('LCA')"
generate_topojson "LI" "ADM0_A3 IN ('LIE')"
generate_topojson "LK" "ADM0_A3 IN ('LKA')"
generate_topojson "LS" "ADM0_A3 IN ('LSO')"
generate_topojson "LT" "ADM0_A3 IN ('LTU')"
generate_topojson "LU" "ADM0_A3 IN ('LUX')"
generate_topojson "LV" "ADM0_A3 IN ('LVA')"
generate_topojson "MO" "ADM0_A3 IN ('MAC')"
generate_topojson "MF" "ADM0_A3 IN ('MAF')"
generate_topojson "MA" "ADM0_A3 IN ('MAR')"
generate_topojson "MC" "ADM0_A3 IN ('MCO')"
generate_topojson "MD" "ADM0_A3 IN ('MDA')"
generate_topojson "MG" "ADM0_A3 IN ('MDG')"
generate_topojson "MV" "ADM0_A3 IN ('MDV')"
generate_topojson "MX" "ADM0_A3 IN ('MEX')"
generate_topojson "MH" "ADM0_A3 IN ('MHL')"
generate_topojson "MK" "ADM0_A3 IN ('MKD')"
generate_topojson "ML" "ADM0_A3 IN ('MLI')"
generate_topojson "MT" "ADM0_A3 IN ('MLT')"
generate_topojson "MM" "ADM0_A3 IN ('MMR')"
generate_topojson "ME" "ADM0_A3 IN ('MNE')"
generate_topojson "MN" "ADM0_A3 IN ('MNG')"
generate_topojson "MP" "ADM0_A3 IN ('MNP')"
generate_topojson "MZ" "ADM0_A3 IN ('MOZ')"
generate_topojson "MR" "ADM0_A3 IN ('MRT')"
generate_topojson "MS" "ADM0_A3 IN ('MSR')"
generate_topojson "MU" "ADM0_A3 IN ('MUS')"
generate_topojson "MW" "ADM0_A3 IN ('MWI')"
generate_topojson "MY" "ADM0_A3 IN ('MYS')"
generate_topojson "NA" "ADM0_A3 IN ('NAM')"
generate_topojson "NC" "ADM0_A3 IN ('NCL')"
generate_topojson "NE" "ADM0_A3 IN ('NER')"
generate_topojson "NF" "ADM0_A3 IN ('NFK')"
generate_topojson "NG" "ADM0_A3 IN ('NGA')"
generate_topojson "NI" "ADM0_A3 IN ('NIC')"
generate_topojson "NU" "ADM0_A3 IN ('NIU')"
generate_topojson "NL" "ADM0_A3 IN ('NLD') AND TYPE_EN NOT LIKE 'Special%'"
generate_topojson "NO" "ADM0_A3 IN ('NOR')"
generate_topojson "NP" "ADM0_A3 IN ('NPL')"
generate_topojson "NR" "ADM0_A3 IN ('NRU')"
generate_topojson "NZ" "ADM0_A3 IN ('NZL')"
generate_topojson "OM" "ADM0_A3 IN ('OMN')"
generate_topojson "PK" "ADM0_A3 IN ('PAK')"
generate_topojson "PA" "ADM0_A3 IN ('PAN')"
generate_topojson "PN" "ADM0_A3 IN ('PCN')"
generate_topojson "PE" "ADM0_A3 IN ('PER')"
generate_topojson "PH" "ADM0_A3 IN ('PHL')"
generate_topojson "PW" "ADM0_A3 IN ('PLW')"
generate_topojson "PG" "ADM0_A3 IN ('PNG')"
generate_topojson "PL" "ADM0_A3 IN ('POL')"
generate_topojson "PR" "ADM0_A3 IN ('PRI')"
generate_topojson "KP" "ADM0_A3 IN ('PRK')"
generate_topojson "PT" "ADM0_A3 IN ('PRT')"
generate_topojson "PY" "ADM0_A3 IN ('PRY')"
generate_topojson "PS" "ADM0_A3 IN ('PSE')"
generate_topojson "PF" "ADM0_A3 IN ('PYF')"
generate_topojson "QA" "ADM0_A3 IN ('QAT')"
generate_topojson "RO" "ADM0_A3 IN ('ROU')"
generate_topojson "RU" "ADM0_A3 IN ('RUS')"
generate_topojson "RW" "ADM0_A3 IN ('RWA')"
generate_topojson "EH" "ADM0_A3 IN ('EH')"
generate_topojson "SA" "ADM0_A3 IN ('SAU')"
generate_topojson "SD" "ADM0_A3 IN ('SDN')"
generate_topojson "SS" "ADM0_A3 IN ('SDS')"
generate_topojson "SN" "ADM0_A3 IN ('SEN')"
generate_topojson "SG" "ADM0_A3 IN ('SGP')"
generate_topojson "GS" "ADM0_A3 IN ('SGS')"
generate_topojson "SH" "ADM0_A3 IN ('SHN')"
generate_topojson "SB" "ADM0_A3 IN ('SLB')"
generate_topojson "SL" "ADM0_A3 IN ('SLE')"
generate_topojson "SV" "ADM0_A3 IN ('SLV')"
generate_topojson "SM" "ADM0_A3 IN ('SMR')"
generate_topojson "SO" "ADM0_A3 IN ('SOM')"
generate_topojson "SO" "ADM0_A3 IN ('SOM')"
generate_topojson "PM" "ADM0_A3 IN ('SPM')"
generate_topojson "RS" "ADM0_A3 IN ('SRB')"
generate_topojson "ST" "ADM0_A3 IN ('STP')"
generate_topojson "SR" "ADM0_A3 IN ('SUR')"
generate_topojson "SK" "ADM0_A3 IN ('SVK')"
generate_topojson "SI" "ADM0_A3 IN ('SVN')"
generate_topojson "SE" "ADM0_A3 IN ('SWE')"
generate_topojson "SZ" "ADM0_A3 IN ('SWZ')"
generate_topojson "SX" "ADM0_A3 IN ('SXM')"
generate_topojson "SC" "ADM0_A3 IN ('SYC')"
generate_topojson "SY" "ADM0_A3 IN ('SYR')"
generate_topojson "TC" "ADM0_A3 IN ('TCA')"
generate_topojson "TD" "ADM0_A3 IN ('TCD')"
generate_topojson "TG" "ADM0_A3 IN ('TGO')"
generate_topojson "TH" "ADM0_A3 IN ('THA')"
generate_topojson "TJ" "ADM0_A3 IN ('TJK')"
generate_topojson "TM" "ADM0_A3 IN ('TKM')"
generate_topojson "TL" "ADM0_A3 IN ('TLS')"
generate_topojson "TO" "ADM0_A3 IN ('TON')"
generate_topojson "TT" "ADM0_A3 IN ('TTO')"
generate_topojson "TN" "ADM0_A3 IN ('TUN')"
generate_topojson "TR" "ADM0_A3 IN ('TUR')"
generate_topojson "TW" "ADM0_A3 IN ('TWN')"
generate_topojson "TZ" "ADM0_A3 IN ('TZA')"
generate_topojson "UG" "ADM0_A3 IN ('UGA')"
generate_topojson "UA" "ADM0_A3 IN ('UKR')"
generate_topojson "UY" "ADM0_A3 IN ('URY')"
generate_topojson "US" "ADM0_A3 IN ('USA')"
generate_topojson "UZ" "ADM0_A3 IN ('UZB')"
generate_topojson "VA" "ADM0_A3 IN ('VAT')"
generate_topojson "VC" "ADM0_A3 IN ('VCT')"
generate_topojson "VE" "ADM0_A3 IN ('VEN')"
generate_topojson "VG" "ADM0_A3 IN ('VGB')"
generate_topojson "VI" "ADM0_A3 IN ('VIR')"
generate_topojson "VN" "ADM0_A3 IN ('VNM')"
generate_topojson "VU" "ADM0_A3 IN ('VUT')"
generate_topojson "WF" "ADM0_A3 IN ('WLF')"
generate_topojson "WS" "ADM0_A3 IN ('WSM')"
generate_topojson "YE" "ADM0_A3 IN ('YEM')"
generate_topojson "ZA" "ADM0_A3 IN ('ZAF')"
generate_topojson "ZM" "ADM0_A3 IN ('ZMB')"
generate_topojson "ZW" "ADM0_A3 IN ('ZWE')"